---
title: "Cam Plots"
author: "Cam Garfield"
date: "4/25/2021"
output: html_document
---

```{r setup, include=FALSE}
library(reshape2)
library(ggplot2)
library(plotly)
library(Lahman)
library(dplyr)
library(gridExtra)
library(viridis)


data(AwardsPlayers)
mvp <- subset(AwardsPlayers, awardID == "Most Valuable Player")
allstar <- AllstarFull

bstats <- battingStats()
mvp <- merge(mvp, bstats, by = c("playerID", "yearID"))
allstar <- merge(allstar, bstats, by = c("playerID", "yearID"))

Bstats <- bstats %>%
  # select the variables that we want left after we filter the data
  select(yearID, H, X2B, X3B, HR, RBI, BA, SlugPct, OBP, OPS, BABIP) %>%
  # select the years from 1871+
  filter(yearID >= 1871) %>%
  group_by(yearID) %>%
  #  summarise_each(funs(sum(., na.rm=TRUE))) %>%
  summarise_all(funs(sum(., na.rm=TRUE))) %>%
  # we summarize by year, and then na.rm takes care of 0's in the data
  mutate(X1 = H-(X2B+X3B+HR)) %>% #create a column for singles
  # we eventually want these as a percentage of hits, so we can do the math now
  mutate(Single = X1/H*100) %>%
  mutate(Double = X2B/H*100) %>%
  mutate(Triple = X3B/H*100) %>%
  mutate(HomeRun = HR/H*100)

```





```{r, fig.height=4}
advStat <- Bstats %>%
  select(yearID, OPS, BABIP, OBP, SlugPct)

advStatYear <- melt(advStat, id.vars = c("yearID"))
head(advStatYear)

statperyear <- ggplot(advStatYear, aes(x = yearID, y = value)) +
  geom_point(color = "red") +
  geom_smooth(method = loess, se = TRUE, color = "black") +
  xlab("Major League Baseball Season") +
  ylab("Overall Values") +
  ggtitle("Cumulative Advanced Hitting Statistics rising over time in the MLB") +
  scale_x_continuous(breaks = c(1870, 1900,  1930,
                                1960, 1990,  2020 )) +
  guides(colour=guide_legend(reverse=TRUE,
                             aes(ggtitle= "Stat Type"))) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
  facet_wrap(. ~ variable, ncol = 2)

statperyear

#ggplot(advStatYear, aes(x = value, fill = yearID)) + geom_density() + facet_grid(. ~ variable)

```


```{r}
mvp2 <- mutate( mvp,
                  yearID = cut(yearID, c(1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020, Inf),
                             labels = c("1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s", "2020") ))

# head(mvp2)

advStat2 <- mutate(advStat, 
                   yearID = cut(yearID, c(1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, Inf),
                             labels = c("1870s", "1880s","1890s", "1900s", "1910s", "1920s", "1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010 - Now") ))

# head(advStat2)

advStatYear2 <- melt(advStat2, id.vars = c("yearID"))
# head(advStatYear2)

# ggplot(mvp2, aes(x = OPS)) +
#    geom_density(alpha = 0, aes(color = yearID))

plotA <- ggplot(advStatYear2, aes(x = yearID, y = value)) +
  geom_bar(stat = "identity") + facet_grid(. ~ variable)

plotA + coord_polar(theta = 'x') +
  theme(axis.text.x = element_text(size = 5),  axis.ticks = element_blank(), axis.text.y = element_blank())

```
