---
title: "Frank Plots"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(readr)
library(dplyr)
library(ggplot2)
library(leaflet)
library(plotly)
library(shinythemes)
shinythemes::themeSelector()
acled <- read_csv('acled.csv')
death_count <- read_csv('death_count.csv')
```

Column {data-width=650, style="height:1000pc;"}
-----------------------------------------------------------------------

### Chart A

```{r}
levels(as.factor(acled$groups))
tab1 <- select(acled, groups, fatality)
death_table <- tab1 %>% 
  group_by(groups) %>%
  count(fatality)
plotType <- function(input) {
  switch(input,
         Count = "stack",
         Proportional = "fill")
}
ui <- shinyUI(
  fluidPage(theme = shinytheme("cerulean"),
    titlePanel("Group"),
    sidebarLayout(
      sidebarPanel(
        sliderInput("min_n", label = "Minimum Number of Incidents by Group",
                  min = 0, max = 20, value = 20, step = 2),
        radioButtons("pType", "Choose plot type:",
                 list("Count", "Proportional"))
      ),
      mainPanel(
        plotOutput("incident_plot")
      )
    )
  ))
  
  
server <- shinyServer(function(input, output) {
  output$incident_plot <- renderPlot({
    colorset = c('Other'='#e6194B','Police'='#ffe119','Police and Other'='#469990',
                 'Police and Sole Perpetrator'='#4363d8','Protesters'='#800000',
                 'Protesters and Other'='#911eb4','Protesters and Police'='#42d4f4',
                 'Protesters and Rioters'='#bfef45','Protesters and Sole Perpetrator'='#fabed4',
                 'Rioters'='#3cb44b','Rioters and Other'='#dcbeff','Rioters and Police'='#aaffc3',
                 'Rioters and Sole Perpetrator'='#f58231','Sole Perpetrator'='#808000',
                 'Sole Perpetrator and Other'='#000075')
    ggplot(death_table %>% filter(n>input$min_n), aes(x=fatality, y=n, fill=groups))+
      geom_bar(position = plotType(input$pType), stat = "identity")+
      scale_fill_manual(values=colorset)+
      labs(x = "Fatality?", y = "Number of Incidents", fill = "Groups Involved")
  })
})
shinyApp(ui, server)
```

#### Key Trends
- Incidents involving a fatality peaked in the summer of 2020 with June being the month with the most fatalities.
- Incidents involving a fatality make up a small proportion of total incidents by month.

#### Key Trends
- Incidents with no fatalities vastly outnumber incidents with fatalities, as can be seen by the count figure.
- The vast majority of non-fatality incidents involve only protests, while the vast majority of incidents with a fatality involved Police officers.

Column {data-width=400, style="height:35pc;"}
-----------------------------------------------------------------------

### Chart B


```{r}
head(death_count)
shinyApp(
  
  ui = fluidPage(theme = shinytheme("cerulean"),
    plotlyOutput("page2chartB")
  ),
  
  
  
  server = function(input, output) {
    
    output$page2chartB <- renderPlotly({
deaths_by_month <- 
  ggplot(death_count, aes(x = yearmon, y = n)) + geom_col() +
  labs(x = "Month", y = "Number of Deaths", title = "Number of Total Deaths by Month") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5))
deaths_by_month <- deaths_by_month + aes(text = paste0("</br> Number of Incidents with Fatalities: ", n,
                                                      "</br> Percent of Total Incidents: ", round(PctTot,2)))
ggplotly(deaths_by_month, tooltip = "text")
    })
  }
)
```
