---
title: "United States Protest Events in 2020"
author: "Hannah Hartnett, Cam Garfield, Frank Driscoll, Cole Guerin"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Link: https://protestplots.shinyapps.io/protest_app/

## Introduction

|           In the year of the 'new normal,' we have experienced many momentous and novel events: a global pandemic; increased awareness of national racial injustices, specifically on the part of the police force, as a result of the murders of countless Black Americans; and a contentious presidential election. This interactive app is intended as an accompaniment to year-end news summaries, to aid investigation of violent and non-violent protests as a response to these significant new phenomena so that organizations such as those working in social justice themed areas may be able to understand the scale and nature of their movements during 2020. Generally speaking, we are seeking to answer this question: how have Americans gathered to react to the formidable national events of 2020? 
</br>
The app was created using data from the Armed Conflict Location and Event Data Project: https://acleddata.com/curated-data-files/. This dataset contains 23238 observations of both armed conflicts and peaceful protest events in 2020; each of these observations captures one day on which an event took place, so a single event can be represented by multiple observations if the event spans multiple days. The dataset has 31 variables, including the type of event, date, location, main actors, number of fatalities, and general descriptive notes, as well as 9 variables we created to aid in data visualization, such as an indicator variable for Black Lives Matter protests.

|           The app is intended for a general audience to use to answer questions such as the following: 
* Did peaceful protests increase or decrease in the United States after the beginning of lockdown orders in March 2020?
* Was there an increase in protests 'with intervention' in the United States after the murders of George Floyd, Ahmaud Arbery, Breonna Taylor, and other Black Americans in the spring of 2020? Where did these protests occur?
* How did the type and location of protests change over the course of the presidential election? Can we identify pro-Trump and pro-Biden protests?
* How did state and non-state actors behave? Are there discernable trends that we notice in their behavior?

## Usage Example

|           The four tabs of our app are used to organize the protest data into intuitive categories for a general audience without a lot of background knowledge on political conflict or data visualization. 

  The first tab of the app contains a map displaying all protest events that occurred in the United States over the course of 2020. Each point represents one day on which the event occurred. Hovering over a point shows the date, type of event, and location, and clicking on the point displays notes about what took place. The slider changes the time frame displayed by the plot, and choosing the Sub-Event Type to the left will also filter this map accordingly. This filtering of the map will allow for users of the app to educate themselves about riots, battles, and protests that they otherwise would not have known about, as well as how these events have shaped American life and politics, by examining the effects of the protests written in the notes. The slider allows users to examine trends in volume and location of protests in certain periods of the year. It is important to note that the graph is only capable of showing one point per location. Zooming further into the map can show more points as the locations become more clearly defined, but if more than one protest occurs during the date range in a specific location, only one set of notes will appear.
  The bar graph alongside the map provides quantitative information about event type. While it is clear that peaceful protests were the most commonly occurring event type, the user can also drill down by date. When exploring different time frames, we can see a large increase in violent demonstrations in the second half of the year. From January to mid-May, there were only 8, but in the rest of the year, during the peak of the Black Lives Matter protests and continuing through the presidential election, there were over 700 violent demonstrations.
  The final plot on the first page shows the number of protests per day by state. We observe many meaningful differences by state; the protests during the peak of the Black Lives Matter movement peak earlier in Minnesota, the home state of George Floyd, than in most other states. We also see that in Florida, a key battleground state in the election, has much higher protest counts throughout the fall, when candidates likely spent increased time campaigning there. Though Washington D.C. experiences significantly fewer protests than most other states, likewise we see protests peak in the fall. It is very important to note that these protest counts can be misleading as they do not take state population into consideration; this graph is intended to compare counts in one state over time, or to compare time series trends between states, but not to compare counts between states.

|           The second tab provides a register to measure the activity of the various actor groups in 2020. From BLM and other racial justice movements to student movements to the increase of AltRight activities this second tab provides an overview of each actor's total participation in protest or conflict events. By selecting any actor group the user desires they are able to compare total activity between groups to be able to understand which groups were the most active in 2020. We see that BLM related activities were by far the most prevalent with other groups such as students, women, police and perhaps surpisingly, the AltRight all having significantly high plots. The second plot in this tab provides the evaluation of sub-event types. So, if we are curious what types of actions Black Lives Matter or Migrant rights protestors were engaged in and how their actions differ from the police or AltRight actors, the dropdown menu allows us to evaluate each to see how frequently they were peacefully protesting or the degree to which their demonstrations were violently broken up. By and large most of the recorded data represents peaceful protests, however we also see in this plot that groups we recognize as historically more disenfranchised faced higher counts and proportions of force used against them while groups such as militias or the AltRight faced less pushback from state actors. This should be surprising given the nature of those two groups and the hateful and often violent rhetoric that they use. So, whie we saw a dramatic rise of racial justice themed events during 2020 as a result of black men and women dying at the hands of state actors like the police, we have also seen dramatic pushback in terms of force used against their protests and the rise of actor groups like the AltRight that openly spew racist rhetoric. 


|           The final tab utilizes another map to dive into the growth of the Black Lives Matter movement. This map has many of the same dynamic options as our opening map, with the exception that the time frame is pre-selected. The Black Lives Matter Movement has grown tremendously in the United States over the course of 2020; based on the time frames, changes in frequency of protests associated with BLM are easily visible. After George Floyd's death, the number of BLM protests sees a dramatic spike and this continues into June. As time wears on for the rest of the year, the number of protests gradually drops, but the protest events are still much more frequent than in the first five months of 2020. The protests associated with George Floyd's death raised awareness and allowed more people to join the cause and protest against other instances of violence against Black lives. In the later months of 2020 not all points directly reference George Floyd in the notes, and instead focus on other American citizens and their stories.

## Design Choices

|           We included the maps so that people using the app could get a feel for where and when these events have happened. Using leaflet was important to form a realism to the map and allow for users to zoom in and out to see the location of these events in great detail. We made the maps filterable by time frame and event type so that the information could be more digestible without too many points at once. Leaflet was also helpful for making very accessible labels and pop-up notes so users could easily read more information on individual events.
  The bar graph accompanying the first map provides the user with additional quantitative information about the protest types, as it is quite difficult to accurately estimate counts by viewing on dots on a map. We utilized plotly to allow the user to mouse over for a count label since some event types have a large disparity in frequency. For example, when looking at strategic developments over the whole year, the scale goes to 20,000 and it is almost impossible to discern that there were 116 events with 'excessive force against protestors.'
  The time series plot features labels of two key events in the timeline of 2020, the death of George Floyd, and the presidential election, to allow users to examine changes in protest frequency as a result of these events. Filtering by state allows the user to explore differences in trends based on location, as protests are often related to regional events.
  We included two bar plots on the second tab so that comparison between groups and event types could be easier. In the first plot depicting overall activity we used a check box feature so that selective comparison between groups was enabled. This allows for the scale of the plot to change for whichever groups we wish to investigate in the data, individually or in a collective. The second plot utilizes the plotly function so that each individual actor group and their sub event data, what type of actions they were engaged in, could be picked out in greater detail. Using a scatter plot was unhelpful in this regard because much of the data existed at similar levels with a hugely disproportionate amount existing at the section for peaceful protests, so without bars the points would get muddled together based on the scale of the data. The data used in this example results from grouping associated actors using keywords to create a list of 23 different actor groups.

## Appendix

|           After our meetings with Jerzy, we worked to combine plots to be able to be modified at the same time as each other using a shiny html widget. We added annotations to the time series plot to mark key events in the US in 2020. We revised our app so that format of our writing and our graph colors were more consistent. Jerzy also helped us to notice some spatial changes that we could make in order to make the app look more clean, such as more readable plot axis and labels, as well has fully viewable plot windows in the app that don't require the user to scroll down.
