---
title: Generate Reproducible & Live HTML and PDF Conference Posters Using RMarkdown
author:
  - name: Frank Driscoll
    affil: 1
  - name: Cam Garfield
    affil: 1
  - name: Cole Guerin
    affil: 1
  - name: Hannah Hartnett
    affil: 1
  
affiliation:
  - num: 1
    address: Statistical Graphics, Colby College
column_numbers: 3
logoright_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
logoleft_name: https&#58;//raw.githubusercontent.com/brentthorne/posterdown/master/images/betterhexlogo.png
output: 
  posterdown::posterdown_html:
    self_contained: false
bibliography: packages.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(Lahman)
library(dplyr)
library(reshape2)
library(ggplot2)
library(gridExtra)
library(viridis)

data(People)
people <- People
head(People)

batting <- Batting
head(batting)

pitching <- Pitching
head(pitching)

fielding <- Fielding
head(fielding)

sums <- batting %>% 
  group_by(playerID) %>% 
  summarise(ab_sum = sum(AB), k_sum = sum(SO), hr_sum = sum(HR))
sums$hr_ab = sums$hr_sum/sums$ab_sum
sums$k_ab = sums$k_sum/sums$ab_sum

by_ID <- sums %>% 
  filter(ab_sum > 1000) %>%
  filter(k_ab>0) %>% 
  filter(hr_ab>0)
  
by_year <- batting %>%
  group_by(yearID) %>%
  summarise(ab = sum(AB), k = sum(SO), hr = sum(HR))

by_year$hr_ab = by_year$hr/by_year$ab
by_year$k_ab = by_year$k/by_year$ab

# establish theme of graphs
baseball_theme <-  theme_gray() + # White background, black and white theme
  theme(axis.text = element_text(size = 10, color = "azure4"),
        text = element_text(size = 10, face = "bold", color = "azure4", family = 'Georgia'))
```

```{r, warning = FALSE, message  = FALSE, echo = FALSE, fig.height = 8, out.width='80%', fig.align = "center"}
# Cole Plot 1

batting <- Batting %>%
  # select the variables that we want left after we filter the data
  select(yearID, H, X2B, X3B, HR) %>%
  # select the years from 1871+
  filter(yearID >= 1871) %>%
  group_by(yearID) %>%
  #  summarise_each(funs(sum(., na.rm=TRUE))) %>%
  summarise_all(funs(sum(., na.rm=TRUE))) %>%
  # we summarize by year, and then na.rm takes care of 0's in the data
  mutate(X1 = H-(X2B+X3B+HR)) %>% #create a column for singles
  # we eventually want these as a percentage of hits, so we can do the math now
  mutate(Single = X1/H*100) %>%
  mutate(Double = X2B/H*100) %>%
  mutate(Triple = X3B/H*100) %>%
  mutate(HomeRun = HR/H*100)

bat <- batting %>%
  select(yearID, Single, Double, Triple, HomeRun)

bat_long <- melt(bat, id.vars = c("yearID"))
head(bat_long)

hitsperyear <- ggplot(bat_long, aes(x=yearID, y= value, col=variable)) +
  geom_line() +
  xlab("Major League Baseball Season") +
  ylab("Percentage") +
  ggtitle("Hits by Type in Major League Baseball") +
  scale_x_continuous(breaks = c(1870, 1885, 1900, 1915, 1930, 1945,
                                1960, 1975, 1990, 2005, 2020 )) +
  scale_y_continuous(breaks = c(0, 25, 50, 75, 100))+
  guides(colour=guide_legend(reverse=TRUE,
                             aes(ggtitle= "Type of Hit"))) +
  baseball_theme +
  scale_colour_manual(values = c('navy', 'indianred1', 'palegreen4', 'mediumpurple3'))


hitsperyear
```

```{r, warning = FALSE, message  = FALSE, echo = FALSE, fig.height = 12, out.width='80%', fig.align = "center"}
# Cole Plot 2

S <- summarize(group_by(Batting, yearID, playerID),
               H=sum(H), AB=sum(AB),
               BB=sum(BB), HBP=sum(HBP, na.rm=TRUE),
               SF=sum(SF, na.rm=TRUE))

ST <- summarize(group_by(Teams, yearID),
                Games = round(mean(W + L)),
                min.AB = 3 * Games)
S2 <- merge(S, ST, by="yearID")
S.regular <- filter(S2, AB >= min.AB)

SD.data <- summarize(group_by(S.regular, yearID),
                     SD.AVG = sd(H / AB),
                     SD.OBP = sd((H + BB + HBP) / (AB + BB + HBP + SF)))

sd_avg <-  ggplot(SD.data, aes(yearID, SD.AVG)) + geom_point() +
  geom_smooth(colour = 'navy', se=FALSE, span=0.35) +
  labs(title = "Standard Deviations of AVG of Regular Hitters",
       x = "Year", y = "SD of Batting Average") +
  baseball_theme

sd_obp <- ggplot(SD.data, aes(yearID, SD.OBP)) +
  geom_point() + geom_smooth(colour = 'navy', se=FALSE, span=0.35) +
  labs(title = "Standard Deviations of OBP of Regular Hitters",
       x = "Year", y = "SD of On Base Percentage") +
  baseball_theme
grid.arrange(sd_avg, sd_obp, ncol = 1)
```


```{r, warning = FALSE, message  = FALSE, echo = FALSE, fig.height = 6, out.width='100%', fig.align = "center"}

# Hannah plot 1
# take continuous variables
batting_continuous <- Batting %>% select(G, AB, R, H, X2B, X3B, HR, RBI, SB, CS, BB, SO, IBB, HBP, SH, SF, GIDP)

cormat <- round(cor(batting_continuous, use = 'complete.obs'), 2)


library(reshape2)
melted_cormat <- melt(cormat)


reorder_cormat <- function(cormat){
  # Use correlation between variables as basis for distance
  dd <- as.dist(1-abs(cormat))
  hc <- hclust(dd)
  cormat <- cormat[hc$order, hc$order]
  return(cormat)
}

# Function to get lower triangle of corr matrix
get_lower_tri <- function(cormat){
  cormat[upper.tri(cormat)] <- NA
  return(cormat)
}

lo_tri_reordered <- cormat %>%
  reorder_cormat %>%
  get_lower_tri %>%
  melt


ggplot(data = lo_tri_reordered, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  labs(x = 'Batting Variable',
       y = 'Batting Variable',
       title = 'Correlation Heat Map for Continuous Batting Variables',
       fill = 'Correlation') +
  baseball_theme +
  theme(axis.text.x = element_text(angle = 45)) +
  scale_fill_gradient2(
  low = "indianred1",
  mid = "white",
  high = "navy",
  midpoint = 0,
  limits = c(-1, 1))

```

# Introduction



## Objectives



# Methods



# Results



# Next Steps


# Conclusion

Try `posterdown` out! Hopefully you like it!

```{r, include=FALSE}
knitr::write_bib(c('knitr','rmarkdown','posterdown','pagedown'), 'packages.bib')
```

# References
